<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rpg</string>
		<string>aspx</string>
		<string>asmx</string>
		<string>rpgle</string>
		<string>sqlrpgle</string>
		
	</array>
	<key>foldingStartMarker</key>
	<string>(?i)(for|if|do|dow|dou|select|begsr|dcl-proc|dcl-pi|dcl-pr|dcl-ds)</string>
	<key>foldingStopMarker</key>
	<string>(?i)(endfor|endif|enddo|endsl|endsr|end-proc|end-pi|end-pr|end-ds)</string>
	<key>grammaurl</key>
	<string>http://manual.macromates.com/en/language_grammars#language_grammars</string>
	<key>name</key>
	<string>rpg RPG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?i)\b(ctl-opt)\b</string>
			<key>end</key>
			<string>;</string>
			<key>name</key>
			<string>keyword.other.rpg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(for|if|do|dow|dou|select|begsr|endsr|endif|endsl|enddo|endfor)\b</string>
			<key>name</key>
			<string>keyword.control.rpg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(dcl-proc|end-proc)\b</string>
			<key>name</key>
			<string>keyword.control.rpg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(when|exsr|else|elseif|other)\b</string>
			<key>name</key>
			<string>keyword.control.rpg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)[\%](abs|addr|alloc|bitand|bitnot|bitor|bitxor|char|check|checkr|date|days|dec|dech|decpos|diff|div|editc|editflt|editw|elem|eof|equal|error|fields|float|found|graph|hours|int|inth|kds|len|lookup|minutes|months|mseconds|nullind|occur|open|paddr|paddr|parms|realloc|rem|replace|scan|seconds|shtdn|size|sqrt|status|str|str|str|subdt|this|time|timestamp|tlookup|trim|triml|trimr|ucs2|uns|unsh|xfoot|xlate|years)\b</string>
			<key>name</key>
			<string>keyword.operator.rpg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(not|acq|add|adddur|alloc|and|bitoff|biton|cab|call|callb|callp|cas|cat|chain|check|checkr|clear|close|commit|comp|dealloc|define|delete|div|dsply|dump|eval|evalr|except|exfmt|exsr|extrct|feod|force|goto|in|iter|kfld|klist|leave|leavesr|lookup|mhhzo|mhlzo|mlhzo|mllzo|monitor|move|movea|movel|mult|mvr|next|occur|on|open|or|other|out|parm|plist|post|read|readc|reade|readp|readpe|realloc|rel|reset|reset|return|rolbk|scan|setgt|setll|setoff|seton|shtdn|sorta|sqrt|sub|subdur|subst|tag|test|testb|testn|testz|time|unlock|update|write|xfoot|xlate|z-add|z-sub)\b</string>
			<key>name</key>
			<string>keyword.operator.rpg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)^\s*(/free|/end-free|/include|/copy)\b</string>
			<key>name</key>
			<string>keyword.operator.rpg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(var)\b</string>
			<key>name</key>
			<string>storage.type.rpg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(dcl-s|dcl-c|dcl-ds|end-ds|dcl-pi|end-pi|dcl-pr|end-pr)\b</string>
			<key>name</key>
			<string>storage.type.rpg</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)[*](ON|OFF|ENTRY|ALL|BLANK|BLANKS|ZERO|ZEROS|HIVAL|LOVAL|PROC|USRCTL)\b</string>
			<key>name</key>
			<string>constant.language.rpg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\%\&gt;</string>
			<key>end</key>
			<string>\&lt;\%</string>
			<key>name</key>
			<string>storage.type.rpg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.rpg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^[ \t]{0,5}[ hfdc][*]</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.block.rpg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\/\/</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.block.rpg</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.rpg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.rpg</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^[ \t]*(exec)\s+(sql)\b</string>
			<key>end</key>
			<string>\;</string>
			<key>name</key>
			<string>support.constant.rpg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>SQL</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^[*]{2,2}(ctdata)?\ </string>
			<key>comment</key>
			<string>Compile time array in the bottom of the source file</string>
			<key>end</key>
			<string>(E-*-O-*-F)</string>
			<key>name</key>
			<string>string.quoted.single.rpg</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.rpg</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.rpg</string>
	<key>uuid</key>
	<string>f43aff62-4f12-4328-9cbb-a8a7a3f1cfef</string>
</dict>
</plist>
